"use strict";

// Stable IDs keep saved work independent of presentation order.
window.INTEGER_EXERCISES = [
  { id:"order", title:"Ordena els enters", prompt:"De menor a major: −4, 7, 0, −9.", type:"ordered", answers:[-9,-4,0,7], hints:["A la recta, els nombres creixen cap a la dreta.","Comença pel negatiu de valor absolut més gran."], steps:["Entre els negatius, −9 és menor que −4.","Els negatius van abans de zero; 7 va després.","−9 < −4 < 0 < 7."], error:"Compara primer els dos negatius; −9 queda més a l’esquerra que −4." },
  { id:"compare", title:"Quin és més gran?", prompt:"Tria el nombre més gran.", choices:["−3","−11","−30","−101"], answers:["−3"], hints:["Entre dos negatius, el més proper al zero és més gran."], steps:["−101 < −30 < −11 < −3.","El més gran és −3, no el que té més xifres."], error:"No comparis només el valor absolut: tots quatre són negatius." },
  { id:"opposite", title:"Oposat i valor absolut", prompt:"Per al nombre 7, calcula les dues quantitats.", labels:["Oposat de 7","Valor absolut de 7"], answers:[-7,7], hints:["L’oposat canvia el signe. El valor absolut mesura la distància al zero."], steps:["L’oposat de 7 és −7 perquè 7 + (−7) = 0.","|7| = 7 perquè és a set unitats del zero."], error:"Oposat i valor absolut són conceptes diferents. El valor absolut mai no és negatiu." },
  { id:"absolute", title:"Valor absolut amb una resta", prompt:"Calcula |−6 − 9|.", answers:[15], hints:["Calcula primer l’expressió dins de les barres.","−6 − 9 = −15. Ara calcula la distància al zero."], steps:["−6 − 9 = −15.","|−15| = 15."], error:"El valor absolut s’aplica al resultat de tota l’expressió interior." },
  { id:"point", title:"Un punt a la recta", prompt:"Quina coordenada té el punt A?", visual:"point", answers:[-5], hints:["Cada marca representa una unitat.","A és a l’esquerra del zero."], steps:["A és cinc marques a l’esquerra de zero.","La seva coordenada és −5."], error:"Compta les marques des de zero i conserva el signe de l’esquerra." },
  { id:"distance", title:"Distància entre dos punts", prompt:"Quina distància hi ha entre −6 i 9?", answers:[15], hints:["La distància és positiva o zero.","Pots sumar el tram de −6 a 0 i el de 0 a 9."], steps:["De −6 a 0 hi ha 6 unitats i de 0 a 9 n’hi ha 9.","6 + 9 = 15; també |9 − (−6)| = 15."], error:"La distància és la separació total, no la suma de les coordenades." },
  { id:"change", title:"Canvi de temperatura", prompt:"La temperatura passa de 7 °C a −4 °C. Quin és el canvi amb signe, en graus?", answers:[-11], hints:["Canvi = valor final − valor inicial."], steps:["Final − inicial = −4 − 7 = −11.","El signe negatiu indica una baixada d’11 °C."], error:"Et demanem el canvi amb signe, no només quants graus de diferència hi ha." },
  { id:"sum-rule", title:"Detecta l’error", prompt:"Una alumna escriu (−3) + (−4) = 7. Quina correcció és vàlida?", choices:["És −7: se sumen els valors absoluts i es manté el signe negatiu.","És 1: es resten sempre els valors absoluts.","És 12: dos negatius es multipliquen.","És 7: dos signes menys sempre donen més."], answers:["És −7: se sumen els valors absoluts i es manté el signe negatiu."], hints:["La regla de signes del producte no és la regla d’una suma."], steps:["Sumem dos nombres negatius: −(3 + 4) = −7.","El resultat 12 correspondria a (−3) · (−4), una altra operació."], error:"Fixa’t en l’operació: és una suma, no un producte." },
  { id:"sum", title:"Signes diferents", prompt:"−18 + 31", answers:[13], hints:["Compara 18 i 31; conserva el signe del valor absolut més gran."], steps:["31 − 18 = 13.","El positiu té més valor absolut; resultat: 13."], error:"Amb signes diferents no sumis els valors absoluts." },
  { id:"subtract", title:"Restar un negatiu", prompt:"−5 − (−12)", answers:[7], hints:["Restar és sumar l’oposat.","Substitueix −(−12) per +12."], steps:["−5 − (−12) = −5 + 12 = 7."], error:"Revisa el signe de la resta davant del nombre negatiu." },
  { id:"group", title:"Agrupar sumands", prompt:"−7 + 12 − 9 + 4", answers:[0], hints:["Agrupa els positius i els negatius."], steps:["12 + 4 = 16 i −7 − 9 = −16.","16 − 16 = 0."], error:"Conserva el signe de cada terme quan l’agrupis." },
  { id:"product", title:"Tres factors", prompt:"(−4) · 3 · (−2)", answers:[24], hints:["Compta els factors negatius.","Dos factors negatius donen un producte positiu."], steps:["(−4) · 3 = −12.","(−12) · (−2) = 24."], error:"Hi ha dos factors negatius: revisa el signe del resultat." },
  { id:"quotient", title:"Divisió exacta", prompt:"(−84) : 7", answers:[-12], hints:["Divideix els valors absoluts i aplica la regla dels signes."], steps:["84 : 7 = 12.","Els signes són diferents: −12."], error:"Un negatiu dividit per un positiu dona negatiu." },
  { id:"chain", title:"Divisions encadenades", prompt:"(−96) : 8 : (−3)", answers:[4], hints:["Les divisions es fan d’esquerra a dreta.","Primer (−96) : 8 = −12."], steps:["(−96) : 8 = −12.","−12 : (−3) = 4."], error:"No agrupis 8 : (−3): l’expressió no té aquests parèntesis." },
  { id:"sum-product", title:"Producte abans que suma", prompt:"6 − 3 · (−4)", answers:[18], hints:["Calcula el producte abans de la resta."], steps:["3 · (−4) = −12.","6 − (−12) = 18."], error:"Primer el producte; després, restar un negatiu és sumar." },
  { id:"zero", title:"Quina expressió no està definida?", prompt:"Tria l’operació que no es pot calcular.", choices:["0 : (−5)","(−5) : 0","(−5) · 0","0 − (−5)"], answers:["(−5) : 0"], hints:["El problema és un divisor igual a zero, no un dividend igual a zero."], steps:["(−5) : 0 no està definida.","Les altres donen, respectivament, 0, 0 i 5."], error:"Zero dividit per un nombre no nul sí que està definit." },
  { id:"combined", title:"Un parèntesi i un producte", prompt:"−3 · (8 − 15) + 4", answers:[25], hints:["Comença pel parèntesi.","8 − 15 = −7."], steps:["−3 · (−7) + 4 = 21 + 4 = 25."], error:"Revisa el signe del producte dels dos negatius." },
  { id:"nested", title:"Dins del claudàtor", prompt:"18 − [7 − (3 − 11)]", answers:[3], hints:["Resol primer 3 − 11.","7 − (−8) no és 7 − 8."], steps:["3 − 11 = −8.","7 − (−8) = 15.","18 − 15 = 3."], error:"Cada resta afecta el resultat complet del seu parèntesi." },
  { id:"division-bracket", title:"Quocient d’un resultat", prompt:"[−18 + 3 · (5 − 9)] : (−6)", answers:[5], hints:["Fes el parèntesi, després el producte i la suma.","El claudàtor val −30."], steps:["5 − 9 = −4; 3 · (−4) = −12.","−18 − 12 = −30.","−30 : (−6) = 5."], error:"La divisió s’aplica a tot el claudàtor." },
  { id:"remove-brackets", title:"Dos signes menys", prompt:"−2 · [5 − 3 · (−4)]", answers:[-34], hints:["Dins del claudàtor, calcula primer el producte.","5 − (−12) = 17."], steps:["3 · (−4) = −12.","5 − (−12) = 17.","−2 · 17 = −34."], error:"No confonguis 5 − (−12) amb 5 − 12." },
  { id:"minimum", title:"Compara quatre resultats", prompt:"Quina expressió té el resultat més petit?", choices:["−4 · 4","(−18) : (−2)","7 − 10","−2 + 1"], answers:["−4 · 4"], hints:["Calcula els quatre resultats abans de comparar-los."], steps:["Els resultats són −16, 9, −3 i −1.","−16 < −3 < −1 < 9; l’expressió és −4 · 4."], error:"Entre resultats negatius, és menor el que queda més lluny del zero cap a l’esquerra." },
  { id:"absolute-combined", title:"Barres i parèntesis", prompt:"|−8 + 3| − |4 − 10| + 2 · (−3)", answers:[-7], hints:["Calcula cada valor absolut abans d’operar fora de les barres."], steps:["|−5| = 5 i |−6| = 6.","2 · (−3) = −6.","5 − 6 − 6 = −7."], error:"Cada valor absolut és positiu, però l’expressió completa pot ser negativa." },
  { id:"long", title:"Jerarquia completa", prompt:"30 : (−5) − 2 · [3 − (8 − 11)]", answers:[-18], hints:["Resol 8 − 11 i després el claudàtor.","El claudàtor és 3 − (−3) = 6."], steps:["30 : (−5) = −6.","8 − 11 = −3; 3 − (−3) = 6.","−6 − 2 · 6 = −18."], error:"El signe menys davant del producte es conserva fins al final." },
  { id:"repair", title:"Localitza el primer pas incorrecte", prompt:"−3 · (2 − 7) = −3 · (−5) = −15. Quin pas falla?", choices:["2 − 7 = −5","(−3) · (−5) = −15","No hi ha cap error"], answers:["(−3) · (−5) = −15"], hints:["Revisa la regla de signes del producte."], steps:["El parèntesi està ben calculat: 2 − 7 = −5.","El producte de dos negatius és positiu: (−3) · (−5) = 15."], error:"El resultat del parèntesi és correcte; revisa el producte final." },
  { id:"substitute", title:"Substitueix una incògnita", prompt:"Calcula −3x + 2(4 − x) quan x = −2.", answers:[18], hints:["Substitueix cada x per (−2), amb parèntesis."], steps:["−3 · (−2) + 2 · [4 − (−2)].","6 + 2 · 6 = 18."], error:"En substituir, 4 − x es converteix en 4 − (−2)." },
  { id:"coefficients", title:"Distribueix i redueix", prompt:"Escriu −2(3x − 4) + 5x en la forma ax + b. Dona a i b.", labels:["Coeficient a","Terme independent b"], answers:[-1,8], hints:["Multiplica −2 per tots dos termes del parèntesi.","Agrupa −6x i 5x."], steps:["−2(3x − 4) + 5x = −6x + 8 + 5x.","= −x + 8. Per tant a = −1 i b = 8."], error:"Distribueix també sobre −4; el terme independent és positiu." },
  { id:"equation", title:"Equació amb coeficient negatiu", prompt:"Resol −3x + 5 = 20.", labels:["x"], answers:[-5], hints:["Resta 5 als dos membres.","Després divideix els dos membres entre −3."], steps:["−3x = 15; x = 15 : (−3) = −5.","Comprovació: −3 · (−5) + 5 = 20."], error:"El divisor de l’últim pas és −3, no 3." },
  { id:"equation-both", title:"Incògnites als dos membres", prompt:"Resol 4 − 2(x − 3) = 3x + 25.", labels:["x"], answers:[-3], hints:["Elimina el parèntesi amb la distributiva.","10 − 2x = 3x + 25. Agrupa les x en un membre."], steps:["4 − 2x + 6 = 3x + 25.","−5x = 15; x = −3.","Comprovació: esquerra 4 − 2(−6) = 16; dreta −9 + 25 = 16."], error:"−2(x − 3) és −2x + 6. Després opera igual als dos membres." },
  { id:"absolute-equation", title:"Dos punts possibles", prompt:"Troba tots els enters x que compleixen |x − 2| = 5.", type:"set", answers:[-3,7], hints:["Busquem els punts a distància 5 de 2.","x − 2 pot ser 5 o −5."], steps:["x − 2 = 5 dona x = 7.","x − 2 = −5 dona x = −3.","Totes dues solucions compleixen l’equació."], error:"Una distància positiva pot correspondre a un punt a cada costat de 2." },
  { id:"parameter", title:"Un nombre amagat", prompt:"Troba l’enter k: −2 · [5 − 3k] = 26.", labels:["k"], answers:[6], hints:["Divideix els dos membres entre −2.","5 − 3k = −13."], steps:["5 − 3k = −13; −3k = −18; k = 6.","Comprovació: −2 · (5 − 18) = −2 · (−13) = 26."], error:"Conserva el signe negatiu quan divideixis entre −2." },
  { id:"context", title:"Reconstrueix el saldo", prompt:"Després de pagar tres rebuts de 18 € i rebre 25 €, un compte queda a −11 €. Quin saldo tenia al principi?", answers:[18], hints:["Anomena x el saldo inicial i escriu els dos canvis amb signe."], steps:["x − 3 · 18 + 25 = −11.","x − 29 = −11; x = 18.","Comprovació: 18 − 54 + 25 = −11 €."], error:"El saldo inicial ha de compensar una variació total de −29 €." },
  { id:"final", title:"Repte final", prompt:"Calcula −{18 − [4 − 3(2 − 5)]} + 24 : (−6) · 2.", answers:[-13], hints:["Resol de dins cap a fora i mantén el menys exterior.","El claudàtor val 13; les claus valen 5."], steps:["2 − 5 = −3; 3 · (−3) = −9.","4 − (−9) = 13; 18 − 13 = 5; −{5} = −5.","24 : (−6) · 2 = −4 · 2 = −8.","−5 − 8 = −13."], error:"La divisió i el producte tenen la mateixa prioritat: calcula’ls d’esquerra a dreta." }
].map((exercise, index) => ({ ...exercise, level: Math.floor(index / 8), number: index + 1 }));

// Only parse explicit numeric answers; never execute a student's expression.
window.IntegerAnswers = {
  normalize: value => String(value).trim().replace(/[−–]/g, "-").replace(/\s+/g, ""),
  integer(value) {
    const s = this.normalize(value);
    return /^[+-]?\d+(?:[.,]0+)?$/.test(s) && Number.isSafeInteger(Number(s.replace(",", "."))) ? Number(s.replace(",", ".")) : null;
  },
  check(exercise, values) {
    if (exercise.choices) return this.normalize(values[0]) === this.normalize(exercise.answers[0]);
    if (exercise.type === "ordered" || exercise.type === "set") {
      const raw = this.normalize(values[0]).split(/[,;<]+/);
      const actual = raw.map(value => this.integer(value));
      if (actual.some(value => value === null) || actual.length !== exercise.answers.length) return false;
      const expected = [...exercise.answers];
      if (exercise.type === "set") { actual.sort((a,b) => a-b); expected.sort((a,b) => a-b); }
      return actual.every((value, i) => value === expected[i]);
    }
    return values.length === exercise.answers.length && values.every((value,i) => this.integer(value) === exercise.answers[i]);
  }
};
